Add parse! to return just the results
manukall/feeder_ex pull request #7
Opened 2016-09-17 10:14 UTC by patrickdavey

Adds the ability to return just the results to the
user assuming a happy path { :ok, feed, _ } else
raises an error

This allows nicer piping of results.. e.g.

HTTPoison.get!(some_url)
|> FeederEx.parse!
|> Enum.map ......

2016-09-17 11:51 UTC, manukall commented on lib/feeder_ex.ex
> +    {:ok, feed, _} = :feeder.stream feed_bin, opts
i think `{:ok, feed, _} = parse(feed_bin)` would be even nicer here. we could avoid some duplication then. sorry for giving you the wrong idea before.

2016-09-17 11:53 UTC, manukall commented on test/feeder_ex_test.exs
> +  end
would be great if you could add a test for the bad case as well. http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Assertions.html#assert_raise/2 could help.

2016-09-17 11:54 UTC, manukall requested changes
hey, thanks again. i'm sorry for giving you a wrong example before. would you be willing to make those two little changes?

2016-09-17 13:15 UTC, patrickdavey commented on lib/feeder_ex.ex
> +    {:ok, feed, _} = :feeder.stream feed_bin, opts
doh, yes of course! Should have engaged brain first ;)

2016-09-17 13:18 UTC, patrickdavey commented on test/feeder_ex_test.exs
> +  end
So, I did do a test locally with a badly formed feed (just `"<xml>"` and nothing else). It raised the following:

```

Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
pry(1)> FeederEx.parse!("<xml>")
** (BadMapError) expected a map, got: nil
    (feeder_ex) lib/feeder_ex/parser.ex:39: FeederEx.Parser.event/2
                xmerl_sax_parser_utf8.erl:3309: :xmerl_sax_parser_utf8.event_callback/2
                xmerl_sax_parser_utf8.erl:121: :xmerl_sax_parser_utf8.parse/2
    (feeder_ex) lib/feeder_ex.ex:26: FeederEx.parse!/1
       (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
          (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6
          (iex) lib/iex/evaluator.ex:128: IEx.Evaluator.do_eval/4
          (iex) lib/iex/evaluator.ex:108: IEx.Evaluator.eval/4
          (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.loop/3
          (iex) lib/iex/evaluator.ex:18: IEx.Evaluator.init/3
          (iex) lib/iex.ex:439: IEx.pry/3
                test/feeder_ex_test.exs:35: FeederExTest."test parse! returns just the parsed results on success"/1
      (ex_unit) lib/ex_unit/runner.ex:296: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
      (ex_unit) lib/ex_unit/runner.ex:246: anonymous fn/3 in ExUnit.Runner.spawn_test/3
```

So, my question is, what would you suggest to feed to the example case for failing. Perhaps leaving it as is and allowing the error to propagate through is actually the right thing?

2016-09-17 13:41 UTC, manukall commented on test/feeder_ex_test.exs
> +  end
`bin_feed = File.read!(@sample_file) |> String.replace("</xml>", "")` seems to work.

i think you discovered a bug in your other case, though. we should catch `feed` being nil in `def event(:endFeed, {feed, entries})` and handle that better.

2016-09-17 14:47 UTC, patrickdavey commented on test/feeder_ex_test.exs
> +  end
I think I'm misunderstanding something here. I tried the above (the replaced `</xml>`) and it still happily parsed the result. So I'm still not quite sure how to create the failing test. 

Anyway, I'll push up the spec I made so far.

2016-09-17 14:49 UTC, patrickdavey commented on test/feeder_ex_test.exs
> +  end
Note, I will of course remove the WIP commit once this is through and squash everything down. It just seems the easiest way to show you what I've tried.

Apologies for my newness at Elixir! thanks for your patience & most useful library :)

2016-09-18 09:19 UTC, manukall commented
i've manually merged your changes and fixed the `:endFeed` event handler to make the raise assertion work. thanks again!

2016-09-18 09:19 UTC, closed without merging

2016-09-18 11:32 UTC, patrickdavey commented
Excellent - thanks @manukall - and for the new version too. It's very nice to be able to contribute back to the Elixir community - here's hoping for lots more!